# Generated by Django 5.0.1 on 2024-02-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_comment',
            name='rate',
            field=models.IntegerField(default=1, verbose_name='Рейтинг'),
        ),
    ]
