# Generated by Django 5.0.1 on 2024-02-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_news_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_description',
            field=models.TextField(default=1, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
